In [1]:
import numpy as np
import time
rng = np.random.default_rng(42)
X = rng.integers(1, 100, size=(1000, 5)).astype('float64')

1. **Циклами.** Реализуй нормализацию через `for` по столбцам и строкам, без векторных операций. Замерь время через `time.perf_counter()`.
2. **Векторно.** То же самое одним выражением, без единого `for`. Понадобятся `X.mean(axis=?)` и `X.std(axis=?)` — какой axis, решай по правилу «сколько чисел должно получиться».
3. **Сравни.** Проверь, что результаты совпадают: `np.allclose(a, b)`. Выведи ускорение.
4. **Проверь формы** на каждом шаге: `X.shape`, `X.mean(axis=...).shape` и форму результата. Напиши в markdown, почему broadcasting здесь сработал — с выравниванием справа налево.
5. **Убедись, что нормализация верна:** у нормализованных столбцов среднее должно быть ≈0, стандартное отклонение ≈1. Проверь и выведи.

1 Способ:

In [2]:
def std_count(vect):
    sum = 0
    for i in vect:
        sum += i**2
    res = sum / 1000
    res = res**(1/2)
    return res
X1 = np.zeros((1000, 5), dtype='float64')
start_time = time.perf_counter()
for j in range(5):
    mean = X.sum(axis=0)[j] / 1000
    std = std_count(X[:, j])
    for k in range(1000):
        X1[k, j] = (X[k, j] - mean) / std
stop_time = time.perf_counter()
time1 = stop_time - start_time
print(time1)
X1

0.003725210000993684


array([[-0.70751135,  0.47569536,  0.26449103, -0.10071614, -0.13069016],
       [ 0.63896353, -0.71249463,  0.35111852, -0.51797615, -0.70063538],
       [ 0.06190287,  0.825163  ,  0.40309501,  0.45563055,  0.37017078],
       ...,
       [-0.75997141,  0.80768962,  0.73227945,  0.75118972,  0.64650785],
       [ 0.27174311,  0.0388608 ,  0.85355793,  0.09052804,  0.23200224],
       [-0.49767111,  0.42327521,  0.55902448,  0.31654388, -0.00979269]],
      shape=(1000, 5))

2 Способ:

In [3]:
X2 = np.zeros((1000, 5), dtype='float64')

start_time = time.perf_counter()
means = X.mean(axis=0)
stds = X.std(axis=0)
print(means)
print(stds)
X2 = (X - means) / stds
stop_time = time.perf_counter()
time2 = stop_time - start_time
print(time2)
X2

[49.46  49.776 49.734 49.793 50.567]
[28.70519814 28.24202231 29.29066821 28.79215433 28.20325355]
0.0008521400159224868


array([[-1.40950081,  0.96395363,  0.52118989, -0.20120064, -0.26830238],
       [ 1.27294018, -1.44380596,  0.69189272, -1.03476106, -1.43838015],
       [ 0.12332261,  1.67211822,  0.79431442,  0.91021324,  0.75994778],
       ...,
       [-1.5140115 ,  1.63670999,  1.44298518,  1.50065186,  1.32725822],
       [ 0.54136536,  0.0787479 ,  1.68196914,  0.18084788,  0.47629257],
       [-0.99145806,  0.85772895,  1.10157951,  0.63235977, -0.02010406]],
      shape=(1000, 5))

<div dir='rtl'>
    Выбрал axis=0 потому что надо избавиться от 1000 в shape = (1000, 5) а 1000 на 0 индексе поэтому я убрал 0 ось, а broadcasting сработал ведь операции   происходили с (1000, 5) (1, 5) - совпадают 5 значит операции проводится
</div>е
Проверяю совпадение и вывожу среднее и среднее отклонение:

In [5]:
np.allclose(X1, X2)
print(f'Средние первого спосба: {X1.mean(axis=0)}, {X1.std(axis=0})
print(f'Средние второго спосба: {X2.mean(axis=0)}, {X2.std(axis=0})

False

По итогу вывожу во сколько раз нумпай быстрее:

In [ ]:
print(f'Numpy быстрее в {time1 / time2} раз')